services:
  - type: web
    name: sentiment-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: true
      - key: FLASK_ENV
        value: production
      - key: STATIC_URL_PATH
        value: /static
      - key: WEB_CONCURRENCY
        value: 1
    staticPublishPath: ./app/static
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: models
      mountPath: /models
      sizeGB: 1 